name: Sync Fork

on:
  schedule:
    - cron: '0 1 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: SunWeb3Sec
          base: main
          head: main
          ignore_fail: true
          auto_approve: false
          auto_merge: true
          retries: 4
          retry_after: 60
